### ISSUE TITLE
TypeError: (0 , tslib__WEBPACK_IMPORTED_MODULE_6__.__decorate) is not a function

### ISSUE THREAD

**Issue by Ben555555** [Gorniv/ngx-universal#73]
As soon as I add

imports: [
    CookieModule.forRoot(),
  ],

I get the following exception:

./node_modules/@gorniv/ngx-universal/fesm2020/gorniv-ngx-universal.mjs:533
LinkService = __decorate([
                        ^

TypeError: (0 , tslib__WEBPACK_IMPORTED_MODULE_6__.__decorate) is not a function
    at Module.955 (./node_modules/@gorniv/ngx-universal/fesm2020/gorniv-ngx-universal.mjs:533:25)
    at __webpack_require__ (./webpack/bootstrap:19:1)
    at Module.63370 (./src/app/app.component.html:2:32)
    at __webpack_require__ (./webpack/bootstrap:19:1)
    at Module.84362 (./src/app/app.module.ts:74:25)
    at __webpack_require__ (./webpack/bootstrap:19:1)
    at Module.23149 (./src/environments/environment.ts:18:1)
    at __webpack_require__ (./webpack/bootstrap:19:1)
    at Module.53226 (./src/environments/environment.ts:18:1)
    at __webpack_require__ (./webpack/bootstrap:19:1)

Node.js v19.2.0

A server error has occurred.
node exited with 1 code.
connect ECONNREFUSED ::1:64898

**Comment by Ben555555** [comment]
I think this was due to this configuration in tsconfig.json:

,
    "paths": {
      "tslib": [ "./node_modules/tslib/tslib.d.ts" ]
    }

It worked after I removed it.
